[feat] 대여 검증 BookApi
yet-another-study-group/study_toy_MSA pull request #15
Opened 2023-07-05 07:11 UTC by 220SRS

- 책 대여 검증 BookApi 구현
- h2를 사용하여 검증 완료
- 테스트 코드 작성 완료

2023-07-05 15:08 UTC, kimyoungi99 requested changes
수고하셨습니다. 반영하고 알려주세연~~

2023-07-05 15:13 UTC, kimyoungi99 reviewed
좀 더 보여서... ㅈㅅ

2023-07-05 15:13 UTC, kimyoungi99 commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +@Transactional
Transactional 어노테이션은 왜 붙이셨나요?
Spring-Test도 아닌데. Spring-Test에서 Transactional 어노테이션을 왜 붙이는지 찾아보세요.

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +@Transactional
실패 테스트를 할 경우 데이터베이스에 더미 데이터가 쌓이는 걸 방지 하고자 사용했습니다. 하지만 제가 사용한 것은 Mokito 테스트로 서비스에서 데이터베이스를 직접적으로 연결하지 않고 더미 데이터를 직접 넣어 사용하기 때문에 Transation을 사용하지 않아도 됩니다. 혹시 있을 상황에 대비해 사용한 것이었는데 애초에 일어날 수 없는 상황일 뿐더러 불필요한 비용이 발생되기에 빼는게 맞습니다. Spring-Test에서는 서비스 레이어 테스트 상황에서 직접 데이터베이스과 연결되기 때문에 필요합니다. 앞서 말했듯 실패하는 상황에서 데이터베이스를 초기화를 해야하기 때문입니다. 하지만 이점은 실패 상황에서만 유의하며 성공 테스트를 진행해도 데이터베이스 더미데이터가 쌓일 수 있기 때문에 DataBaseClean 객체를 구현하여 AfterEach를 사용하는 것이 더 바람직합니다.

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        assertThat(pass).isEqualTo(true);
값과 상관 없이 성공만 되면 끝인 줄 알아서 2, 5로만 테스트를 진행했습니다. 좀 더 여러가지 상황을 테스트 하겠습니다.

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        boolean pass = bookService.verify(bookId);
User 검증, Book 검증을 모두 Pass 해야 하며 이러한 검증 절차 중 하나이기 때문에 Pass로 지었습니다. 하지만 이것은 프로젝트의 전체적인 구조를 아는 사람한테만 이해가 가능한 단어라고 생각합니다. 단독적으로 봤을때는 Pass가 있다면 어딘가 통과를 해야지만 작동되는 로직이 존재하는 것으로 오해를 살 수 있기 때문에 result가 맞는 표현인것 같습니다.

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +    }
null이 들오게 된다면 이것도 마찬가지로 잘못된 인자값이기에 따로 처리 하지 않으며 IllegalArgumentException으로 통합관리해도 괜찮을 거라 생각했습니다. 하지만 지금은 EntityNotFoundException으로 수정했기 때문에 오해를 방지하고자 NullPointException을 사용해야 될 것 같습니다.

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/HistoryFeignTest.java
> +        int quantity = historyFeign.getBookQuantity(2);
이 테스트는 단순히 OpenFeign이 잘 동작하는 확인하고 싶어서 작성했습니다. 테스트 코드와는 목적이 같지 않기에 삭제하겠습니다

2023-07-06 05:57 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/HistoryFeignTest.java
> +        assertThat(quantity).isEqualTo(3);
앞서 말씀 드린데로 단순히 OpenFeign을 테스트하고 싶어 작성한 코드라 많이 미흡합니다. 앞으로는 불필요한 코드들은 삭제하도록 하겠습니다.

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +
확인 부탁드립니다

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/build.gradle
> +	// h2 동작하기 위한 빌드들
확인 부탁드립니다

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/build.gradle
> +	// 이거 없으면 접속 안됌
확인 부탁드립니다

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookController.java
> +        return pass;
확인 부탁드립니다

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +        return stock;
확인 부탁드립니다

2023-07-06 05:59 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +        int borrowedBooks = historyFeign.getBookQuantity(bookId);
확인 부탁드립니다

2023-07-06 08:14 UTC, kimyoungi99 commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        assertThat(pass).isEqualTo(true);
사실 간단한 로직이기 때문에 이정도도 충분하지만 제가 4, 5를 테스트 해보라는 이유는 
미만 값에 대해서만 성공하는지, 같아도 성공하는지를 확인해보면 넓은 영역을 테스트 할 수 있을 것 같아서 말씀드렸어여!

2023-07-06 08:15 UTC, kimyoungi99 commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        boolean pass = bookService.verify(bookId);
pass: false 일 수 있으니 pass도 나쁘지 않아 보이긴 합니당

2023-07-06 08:16 UTC, kimyoungi99 commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +    }
이거는 일단 넘어가는걸로 하죠. 그냥 한번 생각해보라는 거였습니다. 요청에 null이 들어오면 어떻게(어느 레벨에서) 처리 되는지~

2023-07-06 08:18 UTC, kimyoungi99 commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +@Transactional
불필요한 비용이여서 뺀다기 보다는 의미 없이 나중에 문제를 발생시킬 수 있는 코드는 빼야 합니다.(코드를 읽는 입장에서 확인하기 불편하기도 하구요)
@Transaction이 붙어있다는 것은 단순이 테스트에서 영속을 시키지 않는다는 의미가 아니라 테스트 코드에서 트랜잭션을 적용한다는 의미입니다. + databaseclean보다는 사실 DB를 찌르지 않고 test container를 띄우는 등의 방식이 가장 좋기는 하겠네요.

2023-07-06 08:34 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        assertThat(pass).isEqualTo(true);
이해했습니다 단순히 여러가지 값을 넣어보는 것이 아닌 상황에 맞춰서 어느 수준 까지 통과 시키는지를 테스트 하는 거군요 더 나아가 하나의 설명서가 될 수 도 있다고 생각이 듭니다

2023-07-06 08:34 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +    }
확인 했습니다. null이 들어오는 경우 현재 서비스 계층에서 처리되고 있습니다. 생각해 보면 null 같은 경우에는 서비스 계층에 들어가지도 않아도 잘못된 값이라는 것을 알 수 있기 때문에 그전에 처리되면 좋을 것 같습니다. controller에서 validation처리를 통해 null 값을 들어오지 못하도록 막는다면 성능을 개선 시킬 수 있을것 같습니다.

2023-07-06 08:39 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +@Transactional
감사합니다. test Container을 띄우는 방식은 처음 알게 됐습니다. 데이터베이스와 연관된 테스트를 진행해야 될 시 적용해보겠습니다.

2023-07-08 06:19 UTC, kimyoungi99 commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +            NullPointerException e = new NullPointerException();
null pointer exception 보다는 IllegalArgument가 맞는듯합니다. 
추가로 id=0인 경우에 대해 예외적으로 한 이유가 무엇일까요? spring에서 null을 0으로 바꿔서 넣어줘서 인가요? 로직이 조금 이상한거 같네요. 
같이 아래 검증 로직에 태우면 될 것 같아요.

2023-07-08 06:22 UTC, kimyoungi99 commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +        exceptionCheck(bookId);
함수로 하지 말고

```
if (!bookRepository.existsById(bookId))
    throw new EntityNotFoundException();
```
이렇게 하심은 어떠신가요?

2023-07-11 10:03 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +            NullPointerException e = new NullPointerException();
0은 사용자가 아무값도 입력하지 않았을 경우로 생각하여 다른 상황이라고 단순히 판단한것 같습니다. 다시 보면 유저가 아무값을 입력하지 않든, 존재하지 않는 값을 넣는 잘못된 매개변수인 것은 같은 상황인데 굳이 구분할 필요는 없어 보입니다!

2023-07-11 10:04 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +        exceptionCheck(bookId);
저번에 피드백으로 말씀해주신 부분이기 때문에 수정하겠습니다.

2023-07-11 11:51 UTC, 220SRS commented on Book-Service/src/main/java/com/study/Book/Service/BookService.java
> +        exceptionCheck(bookId);
@kimyoungi99  수정사항 확인 부탁드립니다

2023-07-13 03:42 UTC, mewluee commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        long bookId = 2;
테스트 코드 내에 일부 동작이 비슷해서 중복 코드들이 보입니다.
가독성 측면에서 별 문제가 되지 않는 짧은 코드들이어서 따로 중복 제거를 안 하신 걸까요?

2023-07-13 06:00 UTC, 220SRS commented on Book-Service/src/test/java/com/study/Book/Service/BookServiceTest.java
> +        long bookId = 2;
테스트할 데이터를 넣는 부분에서 MockServer에 있는 Book 데이터가 id = 2 인 데이터 밖에 없어서 중복적으로 들어간것 같습니다. 다시 생각해보니 실제 존재하는 데이터랑 상관없이 mockito를 이용하여 결과값을 사용자가 지정하기 때문에 굳이 실제 데이터를 고려하여 입력값을 넣어줄 필요는 없을것 같습니다!

2023-07-22 12:48 UTC, Heo-y-y reviewed
- History API를 받아와 책의 대여 가능한 여부를 보내주는 API 구현

2023-08-17 07:12 UTC, merged